version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: users_database
          MYSQL_USER: root
          MYSQL_PASSWORD: Hemant@123

    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.Added
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query for all tables
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
            sudo mysql -h 127.0.0.1 -u root -pHemant@123 users_database < sql-data/dummy.sql
            sudo mysql -h 127.0.0.1 -u root -pHemant@123 --execute="SELECT * FROM users_database.Persons"
            sudo mysql -h 127.0.0.1 -u root -pHemant@123 --execute="SELECT * FROM users_database.users"
            sudo mysql -h 127.0.0.1 -u root -pHemant@123 --execute="SELECT * FROM users_database.Bill"
      - run:   
          name: Install required packages
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip
      - run :
          name: Build Artifacts
          command: |
            java -version
            cd WebApplication
            sudo apt-get update
            sudo apt install maven
            mvn spring-boot:run

workflows:
  version: 2
  build-deploy:
    jobs:
      - build     