version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:   
          name: Install required packages
          command: |
            sudo apt-get update && sudo apt-get install yum && sudo apt install openjdk-8-jdk wget zip unzip -y
      - run :
          name: Build Artifacts
          command: |
            cd WebApplication
            sudo apt-get update
            sudo apt install maven
            mvn spring-boot:run
