version: 2.1

jobs:
  pr_check_job:
    docker:
      - image: circleci/openjdk:8u171-jdk
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

    steps:
      - checkout
      - run: echo "Running build on master" # run the `echo` command
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 60`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query and verify the output
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
            sudo mysql -h 127.0.0.1 -u user -ppassw0rd test_db < sql-data/dummy.sql
            sudo mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test_db.Persons"
            sudo mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test_db.users"
            sudo mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test_db.Bill"
      - run:   
          name: Install required packages
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip
      - run :
          name: Build Artifacts
          command: |
            java -version
            cd WebApplication
            sudo apt-get update
            sudo apt install maven
            mvn clean install               
                            
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

    steps:
      - checkout
      - run: echo "Running build on master" # run the `echo` command
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 60`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query and verify the output
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
            sudo mysql -h 127.0.0.1 -u user -ppassw0rd test_db < sql-data/dummy.sql
            sudo mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test_db.Persons"
            sudo mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test_db.users"
            sudo mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test_db.Bill"
      - run:   
          name: Install required packages
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip
      - run :
          name: Build Artifacts
          command: |
            java -version
            cd WebApplication
            sudo apt-get update
            sudo apt install maven
            mvn clean install
workflows:
  version: 2
  pr_check:
    jobs:
      - pr_check_job                          
  build-deploy:
    jobs:
      - build