version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:   
          name: Install required packages
          command: |
            sudo apt-get update && sudo apt-get install yum 
      - run :
          name: Build Artifacts
          command: |
            java -version
            cd WebApplication
            sudo apt-get update
            sudo apt install maven
            mvn spring-boot:run
