amazonProperties:
  #endpointUrl: https://s3.us-east-1.amazonaws.com
  #accessKey:
  #secretKey: 
  #bucketName:
  url: ${awsRDS}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
